### ISSUE TITLE
ETL: Include pipelines

### ISSUE THREAD

**Issue by hiddely** [nicolas-kuechler/doe-suite#37]
For a single suite or even a single experiment super etl pipeline, the ability to "include" an etl pipeline from the etl design instead of copying pipelines around.

Often, pipelines will be quite similar, with their etl's requiring little parameter-specific configuration (made easier as well using the $FACTORS$ parameter option).

Choices to make:
1. How should includable pipelines be defined?
Either in separate "pipeline" files, but then we should find a place to define these. Or include them from other suite config files:

```
$ETL$:
  $INCLUDE_PIPELINE$: 
       suite: example02-single
       pipeline: pipeline_name
```
