### ISSUE TITLE
ETL: Experiments wildcard

### ISSUE THREAD

**Issue by hiddely** [nicolas-kuechler/doe-suite#38]
Add option in ETL to apply pipeline to all experiments using a wildcard.

Syntax:
```
$ETL$:
   pipeline:
      experiments: *
      ... etc
```
