### ISSUE TITLE
Add include variables functionality to ETL steps.

### ISSUE THREAD

**Issue by nicolas-kuechler** [nicolas-kuechler/doe-suite#92]
Similar to how variables can be included in the experiment design (with `$INCLUDE_VARS$`), it would be convenient if this also worked within the config of an individual ETL step.
This would be an extension / re-design of the existing `$ETL_VARS$` which currently are not flexible enough because everything that needs to be varied between steps must be defined as a variable. Instead, it would be more expressive to follow the `$INCLUDE_VARS$` approach, which is flexible in the location where variables are included (e.g., under this variable) and also allows to define custom additional variables.  

For example, this would allow defining a color scheme in a central location or in a step with a complex configuration, e.g., `ColumnCrossPlotLoader`, to share a lot of the configuration with another use of the loader.

Example:
```
ColumnCrossPlotLoader:
        metrics:
          time: {value_cols: [base_s_mean], unit_label: sec}

        cum_subplot_config:
        - chart:
            # Maybe support including vars from another (not sure whether that's a good idea)
            $INCLUDE_VARS$: {suite: example07-etl, pipeline: coord_square, step: ColumnCrossPlotLoader, key: [cum_subplot_config, 0, chart] }
            
            tick_params: {axis: x, labelsize: 7}


          label_map:
             custom_label: custom
              # from a yaml file in another location  (here it could be useful if we could define which variables from labels.yml we want, e.g., the label_map from labels
             $INCLUDE_VARS$: labels.yml   
```
